allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js-pure: true
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  axios: ^1.16.0
  postcss: ^8.5.16
packages:
  - apps/*
