allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@swc/core": true
  core-js-pure: true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@sentry/browser-utils@10.65.0"
  - "@sentry/browser@10.65.0"
  - "@sentry/core@10.65.0"
  - "@sentry/feedback@10.65.0"
  - "@sentry/nextjs@10.65.0"
  - "@sentry/node-core@10.65.0"
  - "@sentry/node@10.65.0"
  - "@sentry/opentelemetry@10.65.0"
  - "@sentry/react@10.65.0"
  - "@sentry/replay-canvas@10.65.0"
  - "@sentry/replay@10.65.0"
  - "@sentry/server-utils@10.65.0"
  - "@sentry/vercel-edge@10.65.0"
overrides:
  adm-zip: 0.6.0
  axios: ^1.16.0
  diff: ^5.2.2
  postcss: ^8.5.16
packages:
  - apps/*
